from advent.year_2022.day_22 import *

text = '''        ...#
        .#..
        #...
        ....
...#.......#
........#...
..#....#....
..........#.
        ...#....
        .....#..
        .#......
        ......#.

10R5L5R10L4R5L5'''.split("\n")

def test_monkey_map_1():
    assert monkey_map_1(text) == 6032