from advent.year_2024.day_8 import *

text = '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''.split("\n")

def test_func_1():
    assert func_1(text) == 14

def test_func_2():
    assert func_2(text) == 34
