from advent.year_2024.day_6 import *

text = '''....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...'''.split("\n")

def test_func_1():
    assert func_1(text) == 41

def test_func_2():
    assert func_2(text) == 6